/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gocast_pctest_PeerConnectionTestActivity_AsyncObserverTask */

#ifndef _Included_com_gocast_pctest_PeerConnectionTestActivity_AsyncObserverTask
#define _Included_com_gocast_pctest_PeerConnectionTestActivity_AsyncObserverTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
