/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gocast_pctest_PeerConnectionTestActivity */

#ifndef _Included_com_gocast_pctest_PeerConnectionTestActivity
#define _Included_com_gocast_pctest_PeerConnectionTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gocast_pctest_PeerConnectionTestActivity
 * Method:    signin
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_pctest_PeerConnectionTestActivity_signin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gocast_pctest_PeerConnectionTestActivity
 * Method:    signout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_pctest_PeerConnectionTestActivity_signout
  (JNIEnv *, jobject);

/*
 * Class:     com_gocast_pctest_PeerConnectionTestActivity
 * Method:    call
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_pctest_PeerConnectionTestActivity_call
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gocast_pctest_PeerConnectionTestActivity
 * Method:    hangup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_pctest_PeerConnectionTestActivity_hangup
  (JNIEnv *, jobject);

/*
 * Class:     com_gocast_pctest_PeerConnectionTestActivity
 * Method:    pcObserverWorker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gocast_pctest_PeerConnectionTestActivity_pcObserverWorker
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
