/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gocast_kddidemo_KDDIDemoActivity */

#ifndef _Included_com_gocast_kddidemo_KDDIDemoActivity
#define _Included_com_gocast_kddidemo_KDDIDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_init
  (JNIEnv *, jobject);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    deinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_deinit
  (JNIEnv *, jobject);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    start
 * Signature: (Ljava/lang/String;[Landroid/view/SurfaceView;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_start
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
