/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gocast_kddidemo_KDDIDemoActivity */

#ifndef _Included_com_gocast_kddidemo_KDDIDemoActivity
#define _Included_com_gocast_kddidemo_KDDIDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_init
  (JNIEnv *, jclass);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    deinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_deinit
  (JNIEnv *, jclass);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    connect
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_connect
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_gocast_kddidemo_KDDIDemoActivity
 * Method:    disconnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gocast_kddidemo_KDDIDemoActivity_disconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
